/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  gtk_object_set_data_full (GTK_OBJECT (component), name, \
    gtk_widget_ref (widget), (GtkDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  gtk_object_set_data (GTK_OBJECT (component), name, widget)

GtkWidget*
create_LoginWindow (void)
{
  GtkWidget *LoginWindow;
  GtkWidget *vbox1;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *hseparator1;
  GtkWidget *table1;
  GtkWidget *label3;
  GtkWidget *hostname_entry;
  GtkWidget *label4;
  GtkObject *port_entry_adj;
  GtkWidget *port_entry;
  GtkWidget *hseparator2;
  GtkWidget *table2;
  GtkWidget *label5;
  GtkWidget *username_entry;
  GtkWidget *label6;
  GtkWidget *password_entry;
  GtkWidget *hseparator3;
  GtkWidget *hbuttonbox1;
  GtkWidget *quit_button;
  GtkWidget *login_button;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label7;

  LoginWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_usize (LoginWindow, 250, -2);
  gtk_container_set_border_width (GTK_CONTAINER (LoginWindow), 5);
  gtk_window_set_title (GTK_WINDOW (LoginWindow), _("IGnus Login"));
  gtk_window_set_resizable (GTK_WINDOW (LoginWindow), FALSE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (LoginWindow), vbox1);

  label1 = gtk_label_new (_("<span size=\"xx-large\" weight=\"bold\">IGnus</span>"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (vbox1), label1, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_LEFT);

  label2 = gtk_label_new (_("<span style=\"italic\" size=\"small\">Stick it in the queue and go.</span>"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (vbox1), label2, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label2), 0, 3);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator1, TRUE, TRUE, 0);

  table1 = gtk_table_new (2, 2, TRUE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox1), table1, TRUE, TRUE, 0);

  label3 = gtk_label_new (_("Hostname:"));
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table1), label3, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label3), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (label3), 5, 0);

  hostname_entry = gtk_entry_new ();
  gtk_widget_show (hostname_entry);
  gtk_table_attach (GTK_TABLE (table1), hostname_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label4 = gtk_label_new (_("Port:"));
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table1), label4, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label4), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (label4), 5, 0);

  port_entry_adj = gtk_adjustment_new (263, 0, 65535, 1, 10, 10);
  port_entry = gtk_spin_button_new (GTK_ADJUSTMENT (port_entry_adj), 1, 0);
  gtk_widget_show (port_entry);
  gtk_table_attach (GTK_TABLE (table1), port_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 3);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (port_entry), TRUE);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator2, TRUE, TRUE, 0);

  table2 = gtk_table_new (2, 2, TRUE);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (vbox1), table2, TRUE, TRUE, 0);

  label5 = gtk_label_new (_("Username:"));
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table2), label5, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label5), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (label5), 5, 0);

  username_entry = gtk_entry_new ();
  gtk_widget_show (username_entry);
  gtk_table_attach (GTK_TABLE (table2), username_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label6 = gtk_label_new (_("Password:"));
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table2), label6, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label6), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (label6), 5, 0);

  password_entry = gtk_entry_new ();
  gtk_widget_show (password_entry);
  gtk_table_attach (GTK_TABLE (table2), password_entry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 3);
  gtk_entry_set_visibility (GTK_ENTRY (password_entry), FALSE);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator3, TRUE, TRUE, 0);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbuttonbox1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbuttonbox1), 5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox1), 5);

  quit_button = gtk_button_new_from_stock ("gtk-quit");
  gtk_widget_show (quit_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), quit_button);
  GTK_WIDGET_SET_FLAGS (quit_button, GTK_CAN_DEFAULT);

  login_button = gtk_button_new ();
  gtk_widget_show (login_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), login_button);
  GTK_WIDGET_SET_FLAGS (login_button, GTK_CAN_DEFAULT);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (login_button), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Log In"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox1), label7, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label7), GTK_JUSTIFY_LEFT);

  gtk_signal_connect (GTK_OBJECT (LoginWindow), "destroy",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (quit_button), "clicked",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect_object (GTK_OBJECT (login_button), "clicked",
                             GTK_SIGNAL_FUNC (on_login_button_clicked),
                             GTK_OBJECT (LoginWindow));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (LoginWindow, LoginWindow, "LoginWindow");
  GLADE_HOOKUP_OBJECT (LoginWindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (LoginWindow, label1, "label1");
  GLADE_HOOKUP_OBJECT (LoginWindow, label2, "label2");
  GLADE_HOOKUP_OBJECT (LoginWindow, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (LoginWindow, table1, "table1");
  GLADE_HOOKUP_OBJECT (LoginWindow, label3, "label3");
  GLADE_HOOKUP_OBJECT (LoginWindow, hostname_entry, "hostname_entry");
  GLADE_HOOKUP_OBJECT (LoginWindow, label4, "label4");
  GLADE_HOOKUP_OBJECT (LoginWindow, port_entry, "port_entry");
  GLADE_HOOKUP_OBJECT (LoginWindow, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (LoginWindow, table2, "table2");
  GLADE_HOOKUP_OBJECT (LoginWindow, label5, "label5");
  GLADE_HOOKUP_OBJECT (LoginWindow, username_entry, "username_entry");
  GLADE_HOOKUP_OBJECT (LoginWindow, label6, "label6");
  GLADE_HOOKUP_OBJECT (LoginWindow, password_entry, "password_entry");
  GLADE_HOOKUP_OBJECT (LoginWindow, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (LoginWindow, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (LoginWindow, quit_button, "quit_button");
  GLADE_HOOKUP_OBJECT (LoginWindow, login_button, "login_button");
  GLADE_HOOKUP_OBJECT (LoginWindow, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (LoginWindow, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (LoginWindow, image1, "image1");
  GLADE_HOOKUP_OBJECT (LoginWindow, label7, "label7");

  return LoginWindow;
}

GtkWidget*
create_StorySubmitWindow (void)
{
  GtkWidget *StorySubmitWindow;
  GtkWidget *vbox2;
  GtkWidget *hbox2;
  GtkWidget *label8;
  GtkWidget *topic_entry;
  GtkWidget *hseparator5;
  GtkWidget *scrolledwindow1;
  GtkWidget *story_entry;
  GtkWidget *hseparator4;
  GtkWidget *hbox5;
  GtkWidget *label11;
  GtkWidget *hbuttonbox2;
  GtkWidget *queues_button;
  GtkWidget *quit_button;
  GtkWidget *alignment6;
  GtkWidget *hbox8;
  GtkWidget *image6;
  GtkWidget *label14;
  GtkWidget *clear_button;
  GtkWidget *submit_button;
  GtkWidget *alignment4;
  GtkWidget *hbox6;
  GtkWidget *image4;
  GtkWidget *label12;

  StorySubmitWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_usize (StorySubmitWindow, 600, 300);
  gtk_container_set_border_width (GTK_CONTAINER (StorySubmitWindow), 5);
  gtk_window_set_title (GTK_WINDOW (StorySubmitWindow), _("Submit Story [inews://vogon@icculus.org:263/vogon's stuff]"));

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (StorySubmitWindow), vbox2);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox2, FALSE, TRUE, 0);

  label8 = gtk_label_new (_("Topic:"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox2), label8, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label8), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label8), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (label8), 5, 0);

  topic_entry = gtk_entry_new ();
  gtk_widget_show (topic_entry);
  gtk_box_pack_start (GTK_BOX (hbox2), topic_entry, TRUE, TRUE, 0);

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_show (hseparator5);
  gtk_box_pack_start (GTK_BOX (vbox2), hseparator5, FALSE, TRUE, 5);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);

  story_entry = gtk_text_view_new ();
  gtk_widget_show (story_entry);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), story_entry);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_show (hseparator4);
  gtk_box_pack_start (GTK_BOX (vbox2), hseparator4, FALSE, TRUE, 5);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox5, FALSE, TRUE, 0);

  label11 = gtk_label_new (_("<span size=\"small\" style=\"italic\">IGnus 0.0.1 (Doylestown)</span>\n<span size=\"small\">Stick it in the queue and go</span>"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox5), label11, TRUE, TRUE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);
  gtk_label_set_justify (GTK_LABEL (label11), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label11), 1, 1);
  gtk_misc_set_padding (GTK_MISC (label11), 5, 0);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (hbox5), hbuttonbox2, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_END);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox2), 5);

  queues_button = gtk_button_new_with_mnemonic (_("Q_ueues..."));
  gtk_widget_show (queues_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), queues_button);
  GTK_WIDGET_SET_FLAGS (queues_button, GTK_CAN_DEFAULT);

  quit_button = gtk_button_new ();
  gtk_widget_show (quit_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), quit_button);
  GTK_WIDGET_SET_FLAGS (quit_button, GTK_CAN_DEFAULT);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (quit_button), alignment6);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox8);

  image6 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox8), image6, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("_Quit"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox8), label14, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label14), GTK_JUSTIFY_LEFT);

  clear_button = gtk_button_new_from_stock ("gtk-clear");
  gtk_widget_show (clear_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), clear_button);
  GTK_WIDGET_SET_FLAGS (clear_button, GTK_CAN_DEFAULT);

  submit_button = gtk_button_new ();
  gtk_widget_show (submit_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), submit_button);
  GTK_WIDGET_SET_FLAGS (submit_button, GTK_CAN_DEFAULT);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (submit_button), alignment4);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox6);

  image4 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox6), image4, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("_Submit"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox6), label12, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label12), GTK_JUSTIFY_LEFT);

  gtk_signal_connect (GTK_OBJECT (queues_button), "clicked",
                      GTK_SIGNAL_FUNC (on_queues_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (quit_button), "clicked",
                      GTK_SIGNAL_FUNC (on_quit_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clear_button), "clicked",
                      GTK_SIGNAL_FUNC (on_clear_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (submit_button), "clicked",
                      GTK_SIGNAL_FUNC (on_submit_button_clicked),
                      NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (StorySubmitWindow, StorySubmitWindow, "StorySubmitWindow");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, label8, "label8");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, topic_entry, "topic_entry");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, hseparator5, "hseparator5");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, story_entry, "story_entry");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, label11, "label11");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, queues_button, "queues_button");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, quit_button, "quit_button");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, image6, "image6");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, label14, "label14");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, clear_button, "clear_button");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, submit_button, "submit_button");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, image4, "image4");
  GLADE_HOOKUP_OBJECT (StorySubmitWindow, label12, "label12");

  return StorySubmitWindow;
}

GtkWidget*
create_QueueListWindow (void)
{
  GtkWidget *QueueListWindow;
  GtkWidget *vbox3;
  GtkWidget *frame1;
  GtkWidget *scrolledwindow2;
  GtkWidget *alignment7;
  GtkWidget *queue_list;
  GtkWidget *label15;
  GtkWidget *frame2;
  GtkWidget *table3;
  GtkWidget *qid_label;
  GtkWidget *desc_label;
  GtkWidget *qname_label;
  GtkWidget *home_label;
  GtkWidget *rdf_label;
  GtkWidget *owner_label;
  GtkWidget *ctime_label;
  GtkWidget *digest_label;
  GtkWidget *singleitem_label;
  GtkWidget *label16;
  GtkWidget *hseparator6;
  GtkWidget *hbuttonbox3;
  GtkWidget *selectq_button;
  GtkWidget *alignment8;
  GtkWidget *hbox9;
  GtkWidget *image7;
  GtkWidget *label26;
  GtkWidget *art_list_button;
  GtkWidget *close_button;

  QueueListWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_usize (QueueListWindow, 740, 400);
  gtk_window_set_title (GTK_WINDOW (QueueListWindow), _("Queue List [inews://vogon@icculus.org:263]"));

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (QueueListWindow), vbox3);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox3), frame1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 5);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (frame1), scrolledwindow2);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow2), 5);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);

  alignment7 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), alignment7);

  queue_list = gtk_tree_view_new ();
  gtk_widget_show (queue_list);
  gtk_container_add (GTK_CONTAINER (alignment7), queue_list);
  gtk_tree_view_set_enable_search (GTK_TREE_VIEW (queue_list), FALSE);

  label15 = gtk_label_new (_("<span size=\"small\">Queues</span>"));
  gtk_widget_show (label15);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label15);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);
  gtk_label_set_justify (GTK_LABEL (label15), GTK_JUSTIFY_LEFT);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox3), frame2, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame2), 5);

  table3 = gtk_table_new (5, 4, TRUE);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (frame2), table3);
  gtk_container_set_border_width (GTK_CONTAINER (table3), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 5);

  qid_label = gtk_label_new (_("QID: 3"));
  gtk_widget_show (qid_label);
  gtk_table_attach (GTK_TABLE (table3), qid_label, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (qid_label), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (qid_label), 0, 0.5);

  desc_label = gtk_label_new (_("Description: the only blog with the power of orange oil"));
  gtk_widget_show (desc_label);
  gtk_table_attach (GTK_TABLE (table3), desc_label, 0, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (desc_label), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (desc_label), TRUE);
  gtk_misc_set_alignment (GTK_MISC (desc_label), 0, 0.5);

  qname_label = gtk_label_new (_("Name: vogon's stuff"));
  gtk_widget_show (qname_label);
  gtk_table_attach (GTK_TABLE (table3), qname_label, 1, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (qname_label), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (qname_label), TRUE);
  gtk_misc_set_alignment (GTK_MISC (qname_label), 0, 0.5);

  home_label = gtk_label_new (_("Home: http://goatse.cx"));
  gtk_widget_show (home_label);
  gtk_table_attach (GTK_TABLE (table3), home_label, 0, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (home_label), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (home_label), TRUE);
  gtk_misc_set_alignment (GTK_MISC (home_label), 0, 0.5);

  rdf_label = gtk_label_new (_("RDF: http://goatse.cx/hot_air.rdf"));
  gtk_widget_show (rdf_label);
  gtk_table_attach (GTK_TABLE (table3), rdf_label, 2, 4, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (rdf_label), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (rdf_label), TRUE);
  gtk_misc_set_alignment (GTK_MISC (rdf_label), 0, 0.5);

  owner_label = gtk_label_new (_("Owner: vogon (UID 7)"));
  gtk_widget_show (owner_label);
  gtk_table_attach (GTK_TABLE (table3), owner_label, 0, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (owner_label), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (owner_label), 0, 0.5);

  ctime_label = gtk_label_new (_("Created: 12-31-69 23:59:59"));
  gtk_widget_show (ctime_label);
  gtk_table_attach (GTK_TABLE (table3), ctime_label, 2, 4, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (ctime_label), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (ctime_label), 0, 0.5);

  digest_label = gtk_label_new (_("Digest: http://goatse.cx/hello.jpg"));
  gtk_widget_show (digest_label);
  gtk_table_attach (GTK_TABLE (table3), digest_label, 0, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (digest_label), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (digest_label), TRUE);
  gtk_misc_set_alignment (GTK_MISC (digest_label), 0, 0.5);

  singleitem_label = gtk_label_new (_("Single Item: http://goatse.cx/hello.jpg"));
  gtk_widget_show (singleitem_label);
  gtk_table_attach (GTK_TABLE (table3), singleitem_label, 2, 4, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (singleitem_label), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (singleitem_label), TRUE);
  gtk_misc_set_alignment (GTK_MISC (singleitem_label), 0, 0.5);

  label16 = gtk_label_new (_("<span size=\"small\">Detailed Information</span>"));
  gtk_widget_show (label16);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label16);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);
  gtk_label_set_justify (GTK_LABEL (label16), GTK_JUSTIFY_LEFT);

  hseparator6 = gtk_hseparator_new ();
  gtk_widget_show (hseparator6);
  gtk_box_pack_start (GTK_BOX (vbox3), hseparator6, FALSE, TRUE, 5);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (vbox3), hbuttonbox3, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbuttonbox3), 5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox3), GTK_BUTTONBOX_END);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox3), 5);

  selectq_button = gtk_button_new ();
  gtk_widget_show (selectq_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), selectq_button);
  GTK_WIDGET_SET_FLAGS (selectq_button, GTK_CAN_DEFAULT);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (selectq_button), alignment8);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox9);

  image7 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox9), image7, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Change _Queue"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox9), label26, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label26), GTK_JUSTIFY_LEFT);

  art_list_button = gtk_button_new_with_mnemonic (_("_Articles..."));
  gtk_widget_show (art_list_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), art_list_button);
  GTK_WIDGET_SET_FLAGS (art_list_button, GTK_CAN_DEFAULT);

  close_button = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (close_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), close_button);
  GTK_WIDGET_SET_FLAGS (close_button, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (queue_list), "cursor_changed",
                      GTK_SIGNAL_FUNC (on_queue_list_cursor_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (selectq_button), "clicked",
                      GTK_SIGNAL_FUNC (on_selectq_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (art_list_button), "clicked",
                      GTK_SIGNAL_FUNC (on_art_list_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (close_button), "clicked",
                      GTK_SIGNAL_FUNC (on_close_button_clicked),
                      NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (QueueListWindow, QueueListWindow, "QueueListWindow");
  GLADE_HOOKUP_OBJECT (QueueListWindow, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (QueueListWindow, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (QueueListWindow, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (QueueListWindow, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (QueueListWindow, queue_list, "queue_list");
  GLADE_HOOKUP_OBJECT (QueueListWindow, label15, "label15");
  GLADE_HOOKUP_OBJECT (QueueListWindow, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (QueueListWindow, table3, "table3");
  GLADE_HOOKUP_OBJECT (QueueListWindow, qid_label, "qid_label");
  GLADE_HOOKUP_OBJECT (QueueListWindow, desc_label, "desc_label");
  GLADE_HOOKUP_OBJECT (QueueListWindow, qname_label, "qname_label");
  GLADE_HOOKUP_OBJECT (QueueListWindow, home_label, "home_label");
  GLADE_HOOKUP_OBJECT (QueueListWindow, rdf_label, "rdf_label");
  GLADE_HOOKUP_OBJECT (QueueListWindow, owner_label, "owner_label");
  GLADE_HOOKUP_OBJECT (QueueListWindow, ctime_label, "ctime_label");
  GLADE_HOOKUP_OBJECT (QueueListWindow, digest_label, "digest_label");
  GLADE_HOOKUP_OBJECT (QueueListWindow, singleitem_label, "singleitem_label");
  GLADE_HOOKUP_OBJECT (QueueListWindow, label16, "label16");
  GLADE_HOOKUP_OBJECT (QueueListWindow, hseparator6, "hseparator6");
  GLADE_HOOKUP_OBJECT (QueueListWindow, hbuttonbox3, "hbuttonbox3");
  GLADE_HOOKUP_OBJECT (QueueListWindow, selectq_button, "selectq_button");
  GLADE_HOOKUP_OBJECT (QueueListWindow, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (QueueListWindow, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (QueueListWindow, image7, "image7");
  GLADE_HOOKUP_OBJECT (QueueListWindow, label26, "label26");
  GLADE_HOOKUP_OBJECT (QueueListWindow, art_list_button, "art_list_button");
  GLADE_HOOKUP_OBJECT (QueueListWindow, close_button, "close_button");

  return QueueListWindow;
}

