/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_LoginWindow (void);
GtkWidget* create_StorySubmitWindow (void);
GtkWidget* create_QueueListWindow (void);
GtkWidget* create_ArticleListWindow (void);
